// Generated by LiveScript 1.4.0
(function(){
  var Android, a;
  Android = require('./index').Android;
  a = new Android('phone');
  a.query('ttsSpeak', ['0'], function(data){
    console.log(data);
    return a.close();
  });
  a.ttsSpeak('0');
}).call(this);
